### ISSUE TITLE
Keep a CHANGELOG

### ISSUE THREAD

**Issue by tiagoamaro** [IFTTT/polo#15]
Hey @nettofarah, thank you for this awesome gem :)

This issue is more an idea. I'm finding hard times to check which version has been packaged to Rubygems and which one is the current version on `master` branch.

What do you think in keeping a Changelog? :)

**Comment by nettofarah** [comment]
Hey, @tiagoamaro. This sounds like a great idea!
Not much has changed since the last release though, but still, it would be awesome to have a changelog.

Do you wanna start one and submit a PR?
