### ISSUE TITLE
obfuscate does not work with lambda

### ISSUE THREAD

**Issue by belt-ascendlearning** [IFTTT/polo#24]
<pre>
def intersection(attrs, fields)
  attrs & fields.to_a.flatten.map(&:to_s)
end
</pre>

<code>fields.to_a.flatten.map(&:to_s)</code> does not yield the array-of-strings you are looking for... instead it yields:

<code>
["{:password_digest => #20 < Proc:0x007fccdcb6abb0@RAILS_ROOT/lib/tasks/db_grep_associations.rake:92 (lambda)>}"]
</code>

**Comment by nettofarah** [comment]
hey @belt-ascendlearning, thank you for reporting the bug.
I think this was introduced here: https://github.com/IFTTT/polo/pull/17

Are you running your script against our `master` branch?

**Comment by belt-ascendlearning** [comment]
Yes.

**Comment by nettofarah** [comment]
can you post the code you're trying to run? Including your `Polo.configure` block.

**Comment by nettofarah** [comment]
@belt-ascendlearning I just wrote a new test case for this, and it looks like the strategy works:
https://github.com/IFTTT/polo/blob/master/spec/translator_spec.rb#L40-L48

**Comment by belt-ascendlearning** [comment]
<pre>
Polo.configure do
  obfuscate password_digest: -> {'changeme'}
end
Polo.explore(User, 1, [:roles])
</pre>

**Comment by nettofarah** [comment]
Hi, @belt-ascendlearning 
Just tried it out, and it looks like it works for me.

Here's a sample gist you can use to reproduce it:
https://gist.github.com/nettofarah/9c83964b0eeef291d9fc

You can run it in the command line if you want:
`ruby -e "$(curl -fsSL http://git.io/vRB0Y)"`

**Comment by nettofarah** [comment]
Just managed to reproduce it!
I'll work on a fix.

**Comment by nettofarah** [comment]
Hi, @belt-ascendlearning.
Just fixed the bug with: #25.

Thank you for catching this!
cc @compwron

**Comment by nettofarah** [comment]
Btw, I just pushed a new version of Polo to rubygems.
You should be able to pull `0.2.0` and this should be fixed.

**Comment by nettofarah** [comment]
@belt-ascendlearning can you help us with our survey #19?

**Comment by belt-ascendlearning** [comment]
Confirmed. Thank you verily.

Survey completed... including a gist that others may find useful.

**Comment by nettofarah** [comment]
thank you!

**Comment by compwron** [comment]
Oops. Sorry about that.
