### ISSUE TITLE
NoMethodError: protected method `column_for_attribute' called for

### ISSUE THREAD

**Issue by lacostenycoder** [IFTTT/polo#34]
I'm getting this on every request.  I tried a very simple case:

`inserts = Polo.explore(User, 1)`

I get this error on every model.

I'm using Rails 4.0.0  with Ruby 2.1.2

**Comment by nettofarah** [comment]
hey, @lacostenycoder!
I think this might be due to some recent PR we merged.

I'll look into it as soon as I have a chance.

Thank you for reporting.

**Comment by nettofarah** [comment]
do you mind trying this branch to see if everything works again?
https://github.com/IFTTT/polo/pull/35

**Comment by lacostenycoder** [comment]
That seems to have fixed the problem. :sunglasses:

**Comment by nettofarah** [comment]
Awesome!
I'm glad it worked, @lacostenycoder.

I'll merge the PR and release the fix :)
