### ISSUE TITLE
Postgres support

### ISSUE THREAD

**Issue by volkanunsal** [IFTTT/polo#36]
The SQL file Polo generates doesn't work with Postgres on my setup. I noticed there has been some discussion of support for Postgres already, but only partial support has been implemented. Can anyone fill in the the status of the support for Postgres?

**Comment by nettofarah** [comment]
hello, @volkanunsal.
Polo should work fine with Postgres, except for a few advanced features that are MySQL only.

Can you be a little more specific and post some stack traces to this issue?

**Comment by volkanunsal** [comment]
The override and ignore directives don't work on postgres. That syntax is
mysql specific apparently.

**Comment by nettofarah** [comment]
That's correct, @volkanunsal.
We mention it in the docs: https://github.com/IFTTT/polo#advanced-usage
>  Note: This feature is currently only supported for MySQL databases. (PRs for other databases are welcome!)

**Comment by nettofarah** [comment]
I have looked into working on Posgres support for these features, but I couldn't find any PostgreSQL function that would allow us to build them. I was really bummed when I learned Postgres didn't support these features :(

**Comment by volkanunsal** [comment]
For the ignore directive, this seems to work:

```sql
INSERT INTO table (id, field, field2) SELECT 3, 'C', 'Z' WHERE NOT EXISTS (SELECT 1 FROM table WHERE id=3);
```

**Comment by volkanunsal** [comment]
My only trouble is I haven't been able to figure out how to get Arel to generate INSERT INTO ... SELECT statement.

**Comment by nettofarah** [comment]
This is awesome!
Wanna take a stab and start a PR?

I can help!

**Comment by volkanunsal** [comment]
Another trouble I encountered was the backticks around table and column names. I had to gsub them to make Postgres happy.

**Comment by nettofarah** [comment]
Interesting... My guess is that we'll probably need to implement separate drivers for different database adapters, as these differences start to become more evident.

**Comment by volkanunsal** [comment]
This is a crude version of the code I got to work today using regex substitution. It's really ugly though...

```ruby
def ignore_transform(inserts)
  inserts.map do |insert|
    table_name = insert.match(/INSERT INTO `(.+?)` /)[1]
    id = insert.match(/VALUES \((\d+),/)[1]
    insert = insert.gsub('`', '')
    insert = insert.gsub(/VALUES \((.+)\)$/m, 'SELECT \\1')
    insert << " WHERE NOT EXISTS (SELECT 1 FROM #{table_name} WHERE id=#{id});"
  end
end
```

**Comment by nettofarah** [comment]
This is great progress!
Do you want to start a PR so we can discuss the code a bit more?

**Comment by volkanunsal** [comment]
I'm working on a PR. Another thing I wanted to note is that the SQL translator doesn't work for some native Postgres columns, such as JSON. This column is serialized in YAML format by ActiveRecord, which is not acceptable as a JSON column input to Postgres.

**Comment by dmnelson** [comment]
Hi @volkanunsal, are you working on master? I've submitted a PR in the past (https://github.com/IFTTT/polo/pull/26) that should fix the issues with Postgres (besides `on_duplicate` and other stuff).

I've been using Polo with Postgres, I have `hstore` columns on my schema and it has been working like a charm. I assume `json` would be the same.

**Comment by volkanunsal** [comment]
@dmnelson I just saw that. This may address the issue of JSON columns, but it complicates things a bit since the regex matcher above doesn't work now. Do you have any ideas how to get Arel to spit out something we can use to ignore duplicate rows?

**Comment by volkanunsal** [comment]
I think I solved my own problem. This updated snippet works. We have to change the signature of the method a little bit to receive the records as well.

```ruby
def ignore_transform(inserts, records)
  insert_and_record = inserts.zip(records)
  insert_and_record.map do |insert, record|
    table_name = record.class.arel_table.name
    id = record[:id]
    insert = insert.gsub(/VALUES \((.+)\)$/m, 'SELECT \\1')
    insert << " WHERE NOT EXISTS (SELECT 1 FROM #{table_name} WHERE id=#{id});"
  end
end
```

**Comment by volkanunsal** [comment]
Submitted [a PR](https://github.com/IFTTT/polo/pull/37).
